### ISSUE TITLE
Setup Travis-CI for snapshot builds

### ISSUE THREAD

**Issue by kood1** [FINRAOS/JTAF-XCore#2]
We need to setup Travis-CI builds to continuously build the project and run tests.

**Comment by mibrahim** [comment]
Here's the status: https://travis-ci.org/FINRAOS/JTAF-XCore/builds/97123430

As a high priority we need it to build, and not necessarily deploy snapshots, even though if we can get snapshots in will be nice as well !

**Comment by mibrahim** [comment]
done, and Travis is correctly working
